### PR TITLE
Fix issue in PLAY_PAUSE button handling 

### LINKED ISSUE #1037: Pressing play_pause button sends only OK button press notification
### Bug Report
When an app sends a `SubscribeButton` request with button name set to `PLAY_PAUSE`, it should receive both `OK` & `PLAY_PAUSE` OnButtonPress notifications after the button is pressed on the head unit. However, currently, it only receives `OK`.

##### Reproduction Steps
- Add a listener for `OnButtonPress`
- Send a `SubscribeButton` request with button name set to `PLAY_PAUSE`
- Run the app
- Press the OK/PLAY_PAUSE button on the head unit

##### Expected Behavior
- Both `OK` & `PLAY_PAUSE` OnButtonPress notifications should be received

##### Observed Behavior
- Only `OK` OnButtonPress notifications is received

##### OS & Version Information
* Android Version: 8
* SDL Android Version: 4.8.0 RC3
* Testing Against: Ford SYNC3 TDK

### PR DESCRIPTION
**Pull request by bilal-alsharifi**
Fixes #1037

This PR is **Ready** for review.

### Risk
This PR makes **no** API changes

### Summary
This PR fixes the issue where app receives only `OK` button press notification after subscribing and pressing the `PLAY_PAUSE` button. It also adds `PLAY_PAUSE` button handling to javaSE.

### Testing Plan
- Add a listener for `OnButtonPress`
- Send a `SubscribeButton` request with button name set to `PLAY_PAUSE`
- Run the app
- Press the OK/PLAY_PAUSE button on the head unit
- Confirm that the app receives `OnButtonPress` notifications for both OK & PLAY_PAUSE 
- Repeat the test for the javaSE library
### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java [hunk 1]
```diff
@@ -2064,8 +2064,35 @@ private void handleErrorsFromInternalMessageDispatcher(String info, Exception e)
...
+						RPCRequest request2 = new RPCRequest(request);
+						request2.setParameters(SubscribeButton.KEY_BUTTON_NAME, ButtonName.PLAY_PAUSE);
+						request2.setOnRPCResponseListener(request.getOnRPCResponseListener());
+						sendRPCMessagePrivate(request2);
+						return;
+					}
+				}
+			}
+		}
+
```
Comment (joeygrover) [inline android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java]: Is there a reason we moved this all outside of the try/catch block?

File: android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java [hunk 2]
```diff
@@ -2064,8 +2064,35 @@ private void handleErrorsFromInternalMessageDispatcher(String info, Exception e)
...
+					|| FunctionID.BUTTON_PRESS.toString().equals(request.getFunctionName())) {
+
+				ButtonName buttonName = (ButtonName) request.getObject(ButtonName.class, SubscribeButton.KEY_BUTTON_NAME);
+
+				if (rpcSpecVersion != null && rpcSpecVersion.getMajor() < 5) {
+
+					if (ButtonName.PLAY_PAUSE.equals(buttonName)) {
+						request.setParameters(SubscribeButton.KEY_BUTTON_NAME, ButtonName.OK);
+					}
+				} else { //Newer than version 5.0.0
```
Comment (joeygrover) [inline android/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java]: This would also hit this else if the `rpcSpecVersion` is null

File: javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java [hunk 3]
```diff
@@ -642,6 +642,33 @@ private boolean removeOnRPCRequestListener(FunctionID requestId, OnRPCRequestLis
...
+                        RPCRequest request2 = new RPCRequest(request);
+                        request2.setParameters(SubscribeButton.KEY_BUTTON_NAME, ButtonName.PLAY_PAUSE);
+                        request2.setOnRPCResponseListener(request.getOnRPCResponseListener());
+                        sendRPCMessagePrivate(request2);
+                        return;
+                    }
+                }
+            }
+        }
+
```
Comment (joeygrover) [inline javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java]: Same comments as above regarding try/catch block and second false positive on the else block

File: javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java [hunk 4]
```diff
@@ -643,6 +643,34 @@ private boolean removeOnRPCRequestListener(FunctionID requestId, OnRPCRequestLis
...
+            if (message.getMessageType().equals(RPCMessage.KEY_REQUEST)) {
+                RPCRequest request = (RPCRequest) message;
+                if(FunctionID.SUBSCRIBE_BUTTON.toString().equals(request.getFunctionName())
+                        || FunctionID.UNSUBSCRIBE_BUTTON.toString().equals(request.getFunctionName())
+                        || FunctionID.BUTTON_PRESS.toString().equals(request.getFunctionName())) {
+
+                    ButtonName buttonName = (ButtonName) request.getObject(ButtonName.class, SubscribeButton.KEY_BUTTON_NAME);
+
+                    if (rpcSpecVersion != null){
+                        if (rpcSpecVersion != null && rpcSpecVersion.getMajor() < 5) {
```
Comment (joeygrover) [inline javaSE/src/main/java/com/smartdevicelink/managers/lifecycle/LifecycleManager.java]: unnecessary check for null
