### PR TITLE
Bugfix/issue 687 - send intents explicitly

### LINKED ISSUE #687: Android O, not all SDL Router broadcasts are explicit.
### Bug Report
Upon code inspection, I noticed that there are several places where sendBroadcast() is called to send a message to other SDL apps that still send as implicit broadcasts.  These should be converted to send explicit broadcasts in the same way as was done for the "start" broadcast.

These lines seem to be the ones related to client broadcasts (action = "sdl.router.startservice"):

https://github.com/smartdevicelink/sdl_android/blob/3266a8147f360ccf72882eb90f92a062be19f61f/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L695

https://github.com/smartdevicelink/sdl_android/blob/3266a8147f360ccf72882eb90f92a062be19f61f/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L1255

https://github.com/smartdevicelink/sdl_android/blob/3266a8147f360ccf72882eb90f92a062be19f61f/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L2032

There are a few others, one at least seems to be targeted at other SdlRouterServices and maybe it also should be explicit?

https://github.com/smartdevicelink/sdl_android/blob/3266a8147f360ccf72882eb90f92a062be19f61f/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L277

I am not sure about the other two:

https://github.com/smartdevicelink/sdl_android/blob/3266a8147f360ccf72882eb90f92a062be19f61f/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L201

https://github.com/smartdevicelink/sdl_android/blob/3266a8147f360ccf72882eb90f92a062be19f61f/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L901

If these are just internal then maybe they should be sent using [LocalBroadcastManager](https://developer.android.com/reference/android/support/v4/content/LocalBroadcastManager.html)?

##### OS & Version Information
* Android Version: 8.x+ (O and above)
* SDL Android Version: 4.4.0

### PR DESCRIPTION
**Pull request by brettywhite**
Fixes #687 

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Tested new method on TDK using a local versions of Hello Sdl Android to make sure nothing bad happened. Tested on `targetSdkVersion`'s of 25 and 26

### Summary
- Some broadcast intents in the `SdlRouterService` were being sent implicitly, while android O+ requires them to be sent explicitly. Created a new private method to do just that and modified the broadcasts which need it to use the new method.

- Removed an unnecessary unregister intent in `onTransportDisconnected` in which a broadcast was sent out when there were no registered apps. 

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java [hunk 1]
```diff
@@ -2044,6 +2034,28 @@ private void stopClientPings(){
...
+
+	/**
+	 * Iterate through all of the apps that we know are listening for this intent
+	 * with an explicit intent (necessary for Android O SDK 26+)
+	 *
+	 * @param intent - the intent to send explicitly
+	 * @param isRepeatingPings - If this is coming from a method that will repeat pings,
+	 * we will use a cached list instead of querying each ping
+	 */
+	private void sendExplicitBroadcast(Intent intent, Boolean isRepeatingPings) {
```
Comment (joeygrover) [inline sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java]: Instead of a boolean here, why don't we pass a list of ResolveInfo that we want to send the intents to. If the list is null, we do the normal query of broadcast receivers.  Then for the ping runnable you can cache the list in the runnable itself.

File: sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java [hunk 2]
```diff
@@ -1269,14 +1266,7 @@ public void onTransportDisconnected(TransportType type){
...
 		cachedModuleVersion = -1; //Reset our cached version
-		if(registeredApps== null || registeredApps.isEmpty()){
-			Intent unregisterIntent = new Intent();
-			unregisterIntent.putExtra(HARDWARE_DISCONNECTED, type.name());
-			unregisterIntent.putExtra(TransportConstants.ENABLE_LEGACY_MODE_EXTRA, legacyModeEnabled);
-			unregisterIntent.setAction(TransportConstants.START_ROUTER_SERVICE_ACTION);
-			sendBroadcast(unregisterIntent);
-			//return;
-		}else{
+		if(registeredApps != null){
```
Comment (joeygrover) [inline sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java]: The check for empty list should not have been removed.
