### PR TITLE
Fixes #597 isEmulator

### LINKED ISSUE #597: CI Unit tests broken
The method [`isEmulator`](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android/src/androidTest/java/com/smartdevicelink/test/util/DeviceUtil.java#L6) is no longer working correctly. This causes the CI builds to fail.

### PR DESCRIPTION
**Pull request by joeygrover**
Fixes #597. 

Added more checks that seem to have been changed in the Android v22 emulator.

### CODE REVIEW

File: sdl_android/src/androidTest/java/com/smartdevicelink/test/util/DeviceUtil.java [hunk 1]
```diff
@@ -1,14 +1,18 @@
 package com.smartdevicelink.test.util;
 
 import android.os.Build;
+import android.util.Log;
```
Comment (brettywhite) [inline sdl_android/src/androidTest/java/com/smartdevicelink/test/util/DeviceUtil.java]: do we need this import?

Comment (joeygrover) [reply sdl_android/src/androidTest/java/com/smartdevicelink/test/util/DeviceUtil.java]: No. I will remove. Also have not tagged for review yet. ;)
