### PR TITLE
Expose RAI response and move SdlManager.Builder

### LINKED ISSUE #928: No way to access VehicleType using SDLManager in SDL release 4.7.2
### Bug Report
[No Way to access Vehicletype Information using SDLManager]

##### Reproduction Steps
API not provided to access VehicleType Information

##### Expected Behavior
VehicleType information should be available to Apps.

##### Observed Behavior
NA

##### OS & Version Information
* Android Version: Android OS 9
* SDL Android Version: 4.7.2
* Testing Against: Ford SYNC

##### Test Case, Sample Code, and / or Example App
NA

### PR DESCRIPTION
**Pull request by joeygrover**
Fixes #928 

This PR is **ready** for review.

### Risk
This PR makes ** minor** API changes.

### Testing Plan
 - Connect with Core
- Use new method to retrieve register app interface

### Summary
- Moved the `SdlManager.Builder` class to end of file
- Added public method to retrieve the RegisterAppInterface Response in it's entirety.

##### Enhancements
* Developers should have access to all information that comes back through the RAI response similar to the iOS library.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java [hunk 1]
```diff
@@ -7378,6 +7381,18 @@ public boolean getIconResumed() throws SdlException {
...
 
+	/**
+	 * Method to retrieve the RegisterAppInterface Response message that was sent back from the
+	 * module. It contains various attributes about the connected module and can be used to adapt
+	 * to different module types and their supported features.
+	 *
+	 * @return RegisterAppInterfaceResponse received from the module or null if the app has not yet
+	 * registered with the module.
+	 */
+	public RegisterAppInterfaceResponse getRegisterAppInterfaceResponse(){
```
Comment (BugsBunnyBR) [inline sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java]: is this info available after `SdlManagerListener.onStart()`? Do I need to trigger it in any way?

Comment (joeygrover) [reply sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java]: Yes it is available after the manager starts. For other questions please use the slack channel.
