### PR TITLE
bugfix / issue 652

### LINKED ISSUE #652: RemoteDisplay and video stream cannot be started after stopped
### Bug Report
The remote display fails to start successfully after it has been stopped.  Attempting to start the remote display again will result in a NACK received from SDL core.

##### Reproduction Steps
Create a mobile nav app that uses the remote display within the proxy.
Start the remote display and begin projecting video
Stop the remote display either through the onServiceEnded or internally
Start the remote display again, take note of the failure

##### Expected Behavior
The remote display will start successfully again

##### Observed Behavior
The remote display fails to start the service / project video

### PR DESCRIPTION
**Pull request by mrapitis**
Fixes #652

### CODE REVIEW

File: sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java [hunk 1]
```diff
@@ -6386,9 +6390,8 @@ public void onServiceStarted(SdlSession session, SessionType type, boolean isEnc
 		@Override
 		public void onServiceEnded(SdlSession session, SessionType type) {
 			if(SessionType.NAV.equals(type)){
-				dispose();
+				stopStreaming();
```
Comment (joeygrover) [inline sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java]: Changing from `dispose()` to `stopStreaming()` introduces an unnecessary call to stop the video streaming service. `stopStreaming() -> ISDL.onServiceEnded() -> stopStreaming()` We should try to avoid this in this class rather than relying on downstream efforts. I would suggest either simply check if `remoteDisplay != null` or introduce a new flag that denotes if the `VideoStreamingManager` is currently streaming.

**Comment by mrapitis** [comment]
@joeygrover can you please re-review when you have a moment of time? thanks!
