### PR TITLE
bugfix/554 - Refactor of MultiplexBluetoothTransport to no longer be a singleton.

### LINKED ISSUE #554: NPE in MultiplexBluetoothTransport
I am seeing NullPointerException from [here](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java#L180)
in MultiplexBluetoothTransport.  It seems like this line in the code is doing a null check on an instance of a static variable so I'm guessing that the static variable itself is null.

Here is the stack trace:
```
07-11 10:22:24.014 15384 15384 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.main.tcapp.sdl.SdlRouterService@2052c2cb with Intent { cmp=com.toyota.tcapp/com.main.tcapp.sdl.SdlRouterService (has extras) }: java.lang.NullPointerException: Attempt to read from field 'com.smartdevicelink.transport.MultiplexBluetoothTransport$ConnectThread com.smartdevicelink.transport.MultiplexBluetoothTransport.mConnectThread' on a null object reference
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2881)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.app.ActivityThread.access$2100(ActivityThread.java:144)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5221)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'com.smartdevicelink.transport.MultiplexBluetoothTransport$ConnectThread com.smartdevicelink.transport.MultiplexBluetoothTransport.mConnectThread' on a null object reference
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at com.smartdevicelink.transport.MultiplexBluetoothTransport.start(MultiplexBluetoothTransport.java:180)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at com.smartdevicelink.transport.SdlRouterService.initBluetoothSerialService(SdlRouterService.java:1132)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at com.smartdevicelink.transport.SdlRouterService.onStartCommand(SdlRouterService.java:899)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at com.main.tcapp.sdl.SdlRouterService.onStartCommand(SdlRouterService.java:237)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2864)
07-11 10:22:24.014 15384 15384 E AndroidRuntime: 	... 9 more
```

I wonder if it is due to the change that went in to fix an earlier [issue](https://github.com/smartdevicelink/sdl_android/pull/537/commits/c30dd431c8767bd772ad3139386c623846c5ba9a).   However, it happens on starting the SDL Router service.

I'm using master plus cherry-picked the commit for that fix.

### PR DESCRIPTION
**Pull request by joeygrover**
Fixes #554 

Refactor of `MultiplexBluetoothTransport` to no longer be a singleton. It also cleans up a little of the code in the same class. Changes were also made to the `SdlRouterService` to no longer keep a static reference to the transport class.

### CODE REVIEW

File: sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java [hunk 1]
```diff
@@ -167,7 +164,7 @@ private synchronized void setState(int state) {
```
Comment (Tnnnguyen) [inline sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java]: This method should be removed now that it's not doing anything.

File: sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java [hunk 2]
```diff
@@ -456,7 +453,7 @@ public void run() {
                         case STATE_LISTEN:
                         case STATE_CONNECTING:
                             // Situation normal. Start the connected thread.
-                        	getBluetoothSerialServerInstance().connected(socket, socket.getRemoteDevice());
+                        	connected(socket, socket.getRemoteDevice());
                             
                             break;
                         case STATE_NONE:
```
Comment (Tnnnguyen) [inline sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java]: For the case STATE_CONNECTED, the socket has already been verified to be non-null before entering the switch cases, so this null check statement can be removed.
`if(socket!=null){
                                	socket.close();
                                }
`

File: sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java [hunk 3]
```diff
@@ -257,9 +254,9 @@ public synchronized void connected(BluetoothSocket socket, BluetoothDevice devic
...
         // Cancel the accept thread because we only want to connect to one device
-        if (!keepSocketAlive && getBluetoothSerialServerInstance().mSecureAcceptThread != null) {
-        	getBluetoothSerialServerInstance().mSecureAcceptThread.cancel();
-            getBluetoothSerialServerInstance().mSecureAcceptThread = null;
+        if (!keepSocketAlive && mSecureAcceptThread != null) {
+        	mSecureAcceptThread.cancel();
+            mSecureAcceptThread = null;
         }
 
         // Start the thread to manage the connection and perform transmissions
```
Comment (Tnnnguyen) [inline sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java]: `if(device!=null && device.getName()!=null && device.getName()!="")` this statement behaves the way we expect it to be because the empty string is interned. But it almost always should be: `(.... && device.getName().equals("")`. 
Actually the whole statement can just be: `if (!("").equals(device.getName())`

File: sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java [hunk 4]
```diff
@@ -280,21 +277,21 @@ public synchronized void connected(BluetoothSocket socket, BluetoothDevice devic
         Bundle bundle = new Bundle();
```
Comment (Tnnnguyen) [inline sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java]: We should handle the case of device being null here when calling device.getName().

File: sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java (hunk 3 above)
Comment (joeygrover) [inline sdl_android/src/main/java/com/smartdevicelink/transport/MultiplexBluetoothTransport.java]: Actually I believe that it doesn't matter if the name equals `null` or empty set. It's just about setting the value here. So just `if(device !=null)` will suffice.
